/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as InstallDotshRouteImport } from './routes/install[.]sh'
import { Route as InstallDotps1RouteImport } from './routes/install[.]ps1'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPairRouteImport } from './routes/_authenticated/pair'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as ApiPublicRecordRouteImport } from './routes/api/public/record'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as ApiPublicV1RecordRouteImport } from './routes/api/public/v1/record'
import { Route as ApiPublicRecordIdRouteImport } from './routes/api/public/record.$id'
import { Route as ApiPublicV1RecordIdRouteImport } from './routes/api/public/v1/record.$id'
import { Route as ApiPublicV1PairStartRouteImport } from './routes/api/public/v1/pair/start'
import { Route as ApiPublicV1PairCodeRouteImport } from './routes/api/public/v1/pair/$code'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallDotshRoute = InstallDotshRouteImport.update({
  id: '/install.sh',
  path: '/install.sh',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallDotps1Route = InstallDotps1RouteImport.update({
  id: '/install.ps1',
  path: '/install.ps1',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPairRoute = AuthenticatedPairRouteImport.update({
  id: '/pair',
  path: '/pair',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRecordRoute = ApiPublicRecordRouteImport.update({
  id: '/api/public/record',
  path: '/api/public/record',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1RecordRoute = ApiPublicV1RecordRouteImport.update({
  id: '/api/public/v1/record',
  path: '/api/public/v1/record',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRecordIdRoute = ApiPublicRecordIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPublicRecordRoute,
} as any)
const ApiPublicV1RecordIdRoute = ApiPublicV1RecordIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPublicV1RecordRoute,
} as any)
const ApiPublicV1PairStartRoute = ApiPublicV1PairStartRouteImport.update({
  id: '/api/public/v1/pair/start',
  path: '/api/public/v1/pair/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1PairCodeRoute = ApiPublicV1PairCodeRouteImport.update({
  id: '/api/public/v1/pair/$code',
  path: '/api/public/v1/pair/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/docs': typeof DocsRoute
  '/install.ps1': typeof InstallDotps1Route
  '/install.sh': typeof InstallDotshRoute
  '/mcp': typeof McpRoute
  '/playground': typeof PlaygroundRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/app': typeof AuthenticatedAppRoute
  '/pair': typeof AuthenticatedPairRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/record': typeof ApiPublicRecordRouteWithChildren
  '/api/public/record/$id': typeof ApiPublicRecordIdRoute
  '/api/public/v1/record': typeof ApiPublicV1RecordRouteWithChildren
  '/api/public/v1/pair/$code': typeof ApiPublicV1PairCodeRoute
  '/api/public/v1/pair/start': typeof ApiPublicV1PairStartRoute
  '/api/public/v1/record/$id': typeof ApiPublicV1RecordIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/docs': typeof DocsRoute
  '/install.ps1': typeof InstallDotps1Route
  '/install.sh': typeof InstallDotshRoute
  '/mcp': typeof McpRoute
  '/playground': typeof PlaygroundRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/app': typeof AuthenticatedAppRoute
  '/pair': typeof AuthenticatedPairRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/record': typeof ApiPublicRecordRouteWithChildren
  '/api/public/record/$id': typeof ApiPublicRecordIdRoute
  '/api/public/v1/record': typeof ApiPublicV1RecordRouteWithChildren
  '/api/public/v1/pair/$code': typeof ApiPublicV1PairCodeRoute
  '/api/public/v1/pair/start': typeof ApiPublicV1PairStartRoute
  '/api/public/v1/record/$id': typeof ApiPublicV1RecordIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/docs': typeof DocsRoute
  '/install.ps1': typeof InstallDotps1Route
  '/install.sh': typeof InstallDotshRoute
  '/mcp': typeof McpRoute
  '/playground': typeof PlaygroundRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/pair': typeof AuthenticatedPairRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/record': typeof ApiPublicRecordRouteWithChildren
  '/api/public/record/$id': typeof ApiPublicRecordIdRoute
  '/api/public/v1/record': typeof ApiPublicV1RecordRouteWithChildren
  '/api/public/v1/pair/$code': typeof ApiPublicV1PairCodeRoute
  '/api/public/v1/pair/start': typeof ApiPublicV1PairStartRoute
  '/api/public/v1/record/$id': typeof ApiPublicV1RecordIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/docs'
    | '/install.ps1'
    | '/install.sh'
    | '/mcp'
    | '/playground'
    | '/privacy'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/app'
    | '/pair'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/record'
    | '/api/public/record/$id'
    | '/api/public/v1/record'
    | '/api/public/v1/pair/$code'
    | '/api/public/v1/pair/start'
    | '/api/public/v1/record/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/docs'
    | '/install.ps1'
    | '/install.sh'
    | '/mcp'
    | '/playground'
    | '/privacy'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/app'
    | '/pair'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/record'
    | '/api/public/record/$id'
    | '/api/public/v1/record'
    | '/api/public/v1/pair/$code'
    | '/api/public/v1/pair/start'
    | '/api/public/v1/record/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/docs'
    | '/install.ps1'
    | '/install.sh'
    | '/mcp'
    | '/playground'
    | '/privacy'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/app'
    | '/_authenticated/pair'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/record'
    | '/api/public/record/$id'
    | '/api/public/v1/record'
    | '/api/public/v1/pair/$code'
    | '/api/public/v1/pair/start'
    | '/api/public/v1/record/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DocsRoute: typeof DocsRoute
  InstallDotps1Route: typeof InstallDotps1Route
  InstallDotshRoute: typeof InstallDotshRoute
  McpRoute: typeof McpRoute
  PlaygroundRoute: typeof PlaygroundRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicRecordRoute: typeof ApiPublicRecordRouteWithChildren
  ApiPublicV1RecordRoute: typeof ApiPublicV1RecordRouteWithChildren
  ApiPublicV1PairCodeRoute: typeof ApiPublicV1PairCodeRoute
  ApiPublicV1PairStartRoute: typeof ApiPublicV1PairStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install.sh': {
      id: '/install.sh'
      path: '/install.sh'
      fullPath: '/install.sh'
      preLoaderRoute: typeof InstallDotshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install.ps1': {
      id: '/install.ps1'
      path: '/install.ps1'
      fullPath: '/install.ps1'
      preLoaderRoute: typeof InstallDotps1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pair': {
      id: '/_authenticated/pair'
      path: '/pair'
      fullPath: '/pair'
      preLoaderRoute: typeof AuthenticatedPairRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/record': {
      id: '/api/public/record'
      path: '/api/public/record'
      fullPath: '/api/public/record'
      preLoaderRoute: typeof ApiPublicRecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/record': {
      id: '/api/public/v1/record'
      path: '/api/public/v1/record'
      fullPath: '/api/public/v1/record'
      preLoaderRoute: typeof ApiPublicV1RecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/record/$id': {
      id: '/api/public/record/$id'
      path: '/$id'
      fullPath: '/api/public/record/$id'
      preLoaderRoute: typeof ApiPublicRecordIdRouteImport
      parentRoute: typeof ApiPublicRecordRoute
    }
    '/api/public/v1/record/$id': {
      id: '/api/public/v1/record/$id'
      path: '/$id'
      fullPath: '/api/public/v1/record/$id'
      preLoaderRoute: typeof ApiPublicV1RecordIdRouteImport
      parentRoute: typeof ApiPublicV1RecordRoute
    }
    '/api/public/v1/pair/start': {
      id: '/api/public/v1/pair/start'
      path: '/api/public/v1/pair/start'
      fullPath: '/api/public/v1/pair/start'
      preLoaderRoute: typeof ApiPublicV1PairStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/pair/$code': {
      id: '/api/public/v1/pair/$code'
      path: '/api/public/v1/pair/$code'
      fullPath: '/api/public/v1/pair/$code'
      preLoaderRoute: typeof ApiPublicV1PairCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedPairRoute: typeof AuthenticatedPairRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedPairRoute: AuthenticatedPairRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiPublicRecordRouteChildren {
  ApiPublicRecordIdRoute: typeof ApiPublicRecordIdRoute
}

const ApiPublicRecordRouteChildren: ApiPublicRecordRouteChildren = {
  ApiPublicRecordIdRoute: ApiPublicRecordIdRoute,
}

const ApiPublicRecordRouteWithChildren = ApiPublicRecordRoute._addFileChildren(
  ApiPublicRecordRouteChildren,
)

interface ApiPublicV1RecordRouteChildren {
  ApiPublicV1RecordIdRoute: typeof ApiPublicV1RecordIdRoute
}

const ApiPublicV1RecordRouteChildren: ApiPublicV1RecordRouteChildren = {
  ApiPublicV1RecordIdRoute: ApiPublicV1RecordIdRoute,
}

const ApiPublicV1RecordRouteWithChildren =
  ApiPublicV1RecordRoute._addFileChildren(ApiPublicV1RecordRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DocsRoute: DocsRoute,
  InstallDotps1Route: InstallDotps1Route,
  InstallDotshRoute: InstallDotshRoute,
  McpRoute: McpRoute,
  PlaygroundRoute: PlaygroundRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicRecordRoute: ApiPublicRecordRouteWithChildren,
  ApiPublicV1RecordRoute: ApiPublicV1RecordRouteWithChildren,
  ApiPublicV1PairCodeRoute: ApiPublicV1PairCodeRoute,
  ApiPublicV1PairStartRoute: ApiPublicV1PairStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
